package com.lumatech.timeleaf

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage(val code: String, val displayName: String) {
    PL("pl", "Polski"),
    EN("en", "English")
}

var currentAppLanguage by mutableStateOf(AppLanguage.PL)

enum class AppThemeMode(val key: String) {
    SYSTEM("system"),
    LIGHT("light"),
    DARK("dark")
}

var currentThemeMode by mutableStateOf(AppThemeMode.SYSTEM)

object LocalizedStrings {
    val navTiles: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesje" else "Sessions"
    val navTimer: String get() = if (currentAppLanguage == AppLanguage.PL) "Timer" else "Timer"
    val navProfile: String get() = if (currentAppLanguage == AppLanguage.PL) "Profil" else "Profile"
    val tilesHeaderTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Szybkie Sesje" else "Quick Sessions"
    val tilesHeaderSubtitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Wybierz preset lub stwórz własny czas" else "Pick a preset or create custom focus time"
    val tilesCustomCardTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Utwórz własną sesję" else "Create custom session"
    val tilesCustomCardSub: String get() = if (currentAppLanguage == AppLanguage.PL) "Skonfiguruj własną nazwę i czas" else "Configure custom title & duration"
    val dialogCustomTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Nowa sesja" else "New custom session"
    val dialogSessionNameLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Nazwa nowej sesji..." else "Session name..."
    val btnCancel: String get() = if (currentAppLanguage == AppLanguage.PL) "Anuluj" else "Cancel"
    val btnAdd: String get() = if (currentAppLanguage == AppLanguage.PL) "Dodaj" else "Add"
    val presetQuickTaskTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Szybkie zadanie" else "Quick task"
    val presetPomodoroTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Pomodoro" else "Pomodoro"
    val presetDeepSessionTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Głęboka sesja" else "Deep session"
    val presetHourTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Godzina" else "One Hour"
    val profileAboutTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "O aplikacji TimeLeaf" else "About TimeLeaf"
    val ach1Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Pierwszy krok" else "First Step"
    val ach1Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Włącz timer po raz pierwszy" else "Start the timer for the first time"
    val ach2Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Twórca sesji" else "Session Creator"
    val ach2Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Stwórz własną, spersonalizowaną sesję" else "Create a custom focus session"
    val ach3Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Badacz" else "Explorer"
    val ach3Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Odwiedź sekcję Autorzy aplikacji" else "Visit the App Authors section"
    val ach4Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Maratończyk" else "Marathoner"
    val ach4Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Przepracuj łącznie 5 godzin (300 min)" else "Work for 5 hours in total (300 min)"
    val ach5Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Mistrz Skupienia" else "Focus Master"
    val ach5Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Osiągnij wynik skupienia powyżej 90" else "Reach a focus score above 90"
    val ach6Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Nocny Marek" else "Night Owl"
    val ach6Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Ukończ sesję po godzinie 22:00" else "Complete a session after 10 PM"
    val ach7Title: String get() = if (currentAppLanguage == AppLanguage.PL) "Mistrz Flow" else "Flow Master"
    val ach7Desc: String get() = if (currentAppLanguage == AppLanguage.PL) "Zrealizuj 3 sesje w jeden dzień" else "Complete 3 sessions in one day"
    val settingsTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Ustawienia" else "Settings"
    val settingsLanguageLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Język aplikacji" else "App language"
    val settingsThemeModeLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Tryb motywu" else "Theme mode"
    val themeSystem: String get() = if (currentAppLanguage == AppLanguage.PL) "Systemowy" else "System"
    val themeLight: String get() = if (currentAppLanguage == AppLanguage.PL) "Jasny" else "Light"
    val themeDark: String get() = if (currentAppLanguage == AppLanguage.PL) "Ciemny" else "Dark"
    val settingsSectionNotif: String get() = if (currentAppLanguage == AppLanguage.PL) "Powiadomienia i Dźwięk" else "Notifications & Sound"
    val settingsPushTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Wycisz powiadomienia" else "Mute notifications"
    val settingsSoundTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Wycisz dźwięki alarmu" else "Mute alarm sounds"
    val settingsSectionBehavior: String get() = if (currentAppLanguage == AppLanguage.PL) "Zachowanie Timera" else "Timer Behavior"
    val settingsKeepScreenTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Nie wygaszaj ekranu" else "Keep screen awake"
    val settingsSectionAppearance: String get() = if (currentAppLanguage == AppLanguage.PL) "Wygląd" else "Appearance"
    val btnBack: String get() = if (currentAppLanguage == AppLanguage.PL) "Wróć" else "Back"
    val settingsSectionAbout: String get() = if (currentAppLanguage == AppLanguage.PL) "O aplikacji" else "About"
    val settingsRateApp: String get() = if (currentAppLanguage == AppLanguage.PL) "Oceń naszą aplikację" else "Rate our app"
    val aboutDialogVersion: String get() = if (currentAppLanguage == AppLanguage.PL) "Wersja 1.0.0" else "Version 1.0.0"
    val aboutDialogDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Aplikacja stworzona przez Lumatech. Pomagamy Ci zarządzać czasem i skupieniem podczas codziennych zadań." else "Created by Lumatech. Helping you manage time and focus during daily tasks."
    val btnClose: String get() = if (currentAppLanguage == AppLanguage.PL) "Zamknij" else "Close"
    val settingsAuthorsTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Autorzy aplikacji" else "App Authors"
    val settingsDeleteDataTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Usuń wszystkie dane" else "Delete all data"
    val settingsDeleteDialogTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Usuń wszystkie dane?" else "Delete all data?"
    val settingsDeleteDialogDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Ta operacja jest nieodwracalna. Czy na pewno chcesz usunąć wszystkie dane?" else "This operation is irreversible. Are you sure you want to delete all data?"
    val btnYes: String get() = if (currentAppLanguage == AppLanguage.PL) "Tak" else "Yes"
    val btnNo: String get() = if (currentAppLanguage == AppLanguage.PL) "Nie" else "No"
    val snackDataCleared: String get() = if (currentAppLanguage == AppLanguage.PL) "Wszystkie dane zostały usunięte 🗑️" else "All data cleared 🗑️"
    val settingsHelpTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Pomoc i instrukcja" else "Help & Guide"
    val authorsScreenTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Autorzy aplikacji" else "App Authors"
    val authorMainName: String get() = "Łukasz Matecki"
    val authorRole: String get() = if (currentAppLanguage == AppLanguage.PL) "Główny Twórca & Lead Mobile Developer" else "Lead Creator & Mobile Developer"
    val authorBio: String get() = if (currentAppLanguage == AppLanguage.PL) "Pasjonat nowoczesnych technologii mobilnych, Jetpack Compose oraz tworzenia aplikacji wspierających głębokie skupienie (Deep Work) i produktywność." else "Passionate about modern mobile tech, Jetpack Compose, and creating apps that empower deep work and productivity."
    val authorLinkedinLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Profil LinkedIn" else "LinkedIn Profile"
    val authorEmail1: String get() = "help.lumatech@gmail.com"
    val authorEmail2: String get() = "lukasz.matecki12@gmail.com"
    val authorEmailsLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Adresy e-mail kontaktowe" else "Contact Email Addresses"
    val helpScreenTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Pomoc i instrukcja" else "Help & Guide"
    val helpTabFaq: String get() = if (currentAppLanguage == AppLanguage.PL) "FAQ & Instrukcja" else "FAQ & Guide"
    val helpTabContact: String get() = if (currentAppLanguage == AppLanguage.PL) "Kontakt" else "Contact"
    val contactSupportHeader: String get() = if (currentAppLanguage == AppLanguage.PL) "Kontakt z działem pomocy" else "Contact Support"
    val contactSupportDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Masz pytania, sugestie lub potrzebujesz pomocy z aplikacją TimeLeaf? Skontaktuj się bezpośrednio z naszym zespołem." else "Have questions, suggestions, or need help with TimeLeaf? Reach out directly to our team."
    val contactSupportEmailBtn: String get() = if (currentAppLanguage == AppLanguage.PL) "Wyślij e-mail do wsparcia" else "Email Support Team"
    val reportBugHeader: String get() = if (currentAppLanguage == AppLanguage.PL) "Zgłoszenie błędu" else "Report an Issue"
    val reportBugDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Znalazłeś błąd lub aplikacja działa nieprawidłowo? Wyślij nam zgłoszenie wraz z opisem." else "Found a bug or experiencing unexpected behavior? Send us a bug report with details."
    val reportBugEmailBtn: String get() = if (currentAppLanguage == AppLanguage.PL) "Zgłoś błąd przez e-mail" else "Send Bug Report"
    val faq1Q: String get() = if (currentAppLanguage == AppLanguage.PL) "Jak działa timer skupienia?" else "How does the focus timer work?"
    val faq1A: String get() = if (currentAppLanguage == AppLanguage.PL) "Wybierz preset lub własną sesję z zakładki Sesje, a następnie przejdź do Timera i dotknij okręgu, aby uruchomić odliczanie." else "Pick a preset or custom session from the Sessions tab, then go to the Timer tab and tap the circle to start countdown."
    val faq2Q: String get() = if (currentAppLanguage == AppLanguage.PL) "Jak usuwać własne sesje?" else "How to delete custom sessions?"
    val faq2A: String get() = if (currentAppLanguage == AppLanguage.PL) "Przy każdej stworzonej przez Ciebie sesji znajduje się ikonka kosza obok nazwy. Kliknij ją, aby usunąć wybraną sesję." else "Each custom session card has a trash icon next to its title. Click it to delete that specific session."
    val faq3Q: String get() = if (currentAppLanguage == AppLanguage.PL) "Jak zmienić motyw i język?" else "How to change theme and language?"
    val faq3A: String get() = if (currentAppLanguage == AppLanguage.PL) "Przejdź do Ustawień. Tam znajdziesz rozwijane menu wyboru języka (Polski/English) oraz trybu motywu (Systemowy, Jasny, Ciemny)." else "Go to Settings. There you will find expandable dropdown menus for Language (Polish/English) and Theme mode (System, Light, Dark)."
    val faq4Q: String get() = if (currentAppLanguage == AppLanguage.PL) "Czym jest tryb DND / skupienia?" else "What is Focus / DND mode?"
    val faq4A: String get() = if (currentAppLanguage == AppLanguage.PL) "Podczas aktywnego odliczania TimeLeaf pomaga Ci zachować głębokie skupienie, wyciszając powiadomienia i utrzymując ekran włączony (jeśli opcja jest włączona)." else "During active countdown, TimeLeaf helps you stay in deep focus by muting notifications and keeping the screen awake (if enabled)."
    val hintSessionName: String get() = if (currentAppLanguage == AppLanguage.PL) "Nazwa sesji:" else "Session name:"
    val hintSelectIcon: String get() = if (currentAppLanguage == AppLanguage.PL) "Wybierz ikonę:" else "Select icon:"
    val hintSelectDuration: String get() = if (currentAppLanguage == AppLanguage.PL) "Wybór czasu trwania:" else "Select duration:"
    val profileLevelInfoTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Poziom 3 • 1200 XP" else "Level 3 • 1200 XP"
    val profileLevelInfoDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Posiadasz 1200 XP. Do następnego poziomu brakuje Ci 300 XP. Kontynuuj sesje skupienia, aby zdobywać nagrody!" else "You have 1200 XP. 300 XP needed for next level. Continue focus sessions to earn rewards!"
    val profileScoreTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Wynik Skupienia" else "Focus Score"
    val profileScoreDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Twój wskaźnik skupienia bazuje na ukończonych sesjach i regularności. Aktualny wynik: " else "Your focus score is based on completed sessions and consistency. Current score: "
    val profileStreakTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Dni z rzędu (Streak)" else "Streak (Days in a row)"
    val profileStreakDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Utrzymujesz regularne sesje skupienia przez: " else "You've maintained regular focus sessions for: "
    val profileSessionsTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Ukończone sesje" else "Completed Sessions"
    val profileSessionsDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Liczba pomyślnie ukończonych sesji skupienia: " else "Number of successfully completed focus sessions: "
    val profileTimeTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Całkowity czas skupienia" else "Total Focus Time"
    val profileChartTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Aktywność w tym tygodniu" else "Weekly Activity"
    val profileChartDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Wykres przedstawia Twoją aktywność w poszczególnych dniach tygodnia. Każda ukończona sesja zwiększa Twój wskaźnik." else "The chart shows your activity across days of the week. Every completed session increases your score."
    val snackPressAgainToExit: String get() = if (currentAppLanguage == AppLanguage.PL) "Naciśnij ponownie 'Wróć', aby wyjść z aplikacji" else "Press back again to exit"

    // New Centralized Strings
    val timerStartedToast: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesja rozpoczęta" else "Session started"
    val timerPausedToast: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesja wstrzymana" else "Session paused"
    val timerResumedToast: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesja wznowiona" else "Session resumed"
    val timerResetToast: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesja zresetowana" else "Session reset"
    val timerCompletedToast: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesja zakończona! Statystyki zaktualizowane" else "Session completed! Stats updated 🎉"
    val timerTapToStart: String get() = if (currentAppLanguage == AppLanguage.PL) "Dotknij, aby rozpocząć" else "Tap to start"
    val timerFocusing: String get() = if (currentAppLanguage == AppLanguage.PL) "Skup się..." else "Focus..."
    val timerPausedLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Sesja wstrzymana" else "Session paused"
    val timerDndMode: String get() = if (currentAppLanguage == AppLanguage.PL) "Nie przeszkadzać" else "Do not disturb"
    val timerStopDialogTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Zakończyć sesję?" else "End session?"
    val timerStopDialogDesc: String get() = if (currentAppLanguage == AppLanguage.PL) "Obecny postęp czasu zostanie zresetowany. Czy na pewno chcesz przerwać?" else "Current progress will be reset. Are you sure you want to stop?"
    val timerBtnCancel: String get() = if (currentAppLanguage == AppLanguage.PL) "Anuluj" else "Cancel"
    val timerBtnStop: String get() = if (currentAppLanguage == AppLanguage.PL) "Zakończ" else "End"

    val profileWelcome: String get() = if (currentAppLanguage == AppLanguage.PL) "Witaj w profilu!" else "Welcome to Profile!"
    val profileTasksTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Zadania" else "Tasks"
    val profileNoTasks: String get() = if (currentAppLanguage == AppLanguage.PL) "Brak zadań na dziś. Odpoczywaj!" else "No tasks for today. Rest up!"
    val profileAddTaskPlaceholder: String get() = if (currentAppLanguage == AppLanguage.PL) "Wpisz zadanie..." else "Enter task..."
    val profileAddNewTask: String get() = if (currentAppLanguage == AppLanguage.PL) "Dodaj nowe zadanie..." else "Add new task..."
    val profileShortcutsTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Skróty" else "Shortcuts"
    val profileStatsTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Statystyki" else "Statistics"
    val profileStatFocus: String get() = if (currentAppLanguage == AppLanguage.PL) "Skupienie" else "Focus"
    val profileStatDays: String get() = if (currentAppLanguage == AppLanguage.PL) "Dni" else "Days"
    val profileStatTime: String get() = if (currentAppLanguage == AppLanguage.PL) "Czas" else "Time"
    val profileLevelProgressionTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Rozpiska Poziomów" else "Level Progression"
    val profileCurrentLevel: String get() = if (currentAppLanguage == AppLanguage.PL) "Twój obecny poziom" else "Your current level"
    val profileYourLevelBadge: String get() = if (currentAppLanguage == AppLanguage.PL) "Twój poziom" else "Your level"
    val profileAchievementsTitle: String get() = if (currentAppLanguage == AppLanguage.PL) "Osiągnięcia" else "Achievements"
    val profileAchievementsSub: String get() = if (currentAppLanguage == AppLanguage.PL) "Zdobywaj nagrody za swoją produktywność" else "Earn rewards for your productivity"
    fun profileExpNeeded(nextTitle: String, exp: Int): String =
        if (currentAppLanguage == AppLanguage.PL) "Do kolejnego poziomu brakuje Ci $exp XP"
        else "You need $exp XP for next level"

    val tilesGoalLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Dzisiejszy cel" else "Today's Goal"
    val tilesFocusTimeLabel: String get() = if (currentAppLanguage == AppLanguage.PL) "Czas skupienia" else "Focus Time"
}
